DELETE http://localhost:3003/api/blogs/69fbfa1e203b8be64a3d5b92
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxIiwiaWQiOiI2OWZhNjkyYmQ0NGIzMmVhNzc5YjEwY2QiLCJpYXQiOjE3NzgxODU2MTcsImV4cCI6MTc3ODE4OTIxN30.5CAZIYoK0tMqATLmNvhUQhbyxx5dhnNg0KTK6I-GO5E